SpotBugsHtmlReport: getting file from path should happen in getter
KengoTODA/spotbugs-gradle-plugin-v2 pull request #37
Opened 2020-01-09 21:33 UTC by rpalcolea

`SpotBugsHtmlReport`: getting file from path should happen in getter  instead of setter to prevent resolving a configuration and slow/break a build that has opinions in resolution strategy. 

This should fix https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues/33

2020-01-09 21:37 UTC, rpalcolea commented
Build failed becase of sonar:

```
> Task :sonarqube FAILED
21 actionable tasks: 21 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> You're not authorized to run analysis. Please contact the project administrator.

```

2020-01-11 02:02 UTC, KengoTODA requested changes

2020-01-11 02:02 UTC, KengoTODA commented on src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.java
> +          "Specified stylesheet ({}) found in spotbugs configuration: {}",
At this moment we're not sure that the spotbugs jar file contains specified stylesheet or not, right?
I feel this log message is not so intuitive.

2020-01-11 11:30 UTC, KengoTODA commented
I've disabled SonarQube since it's under maintenance. Merge the latest `origin/master` then the build should pass.

2020-01-13 11:18 UTC, KengoTODA commented
Created #45 with a functional test to reproduce.

2020-01-13 11:18 UTC, closed without merging