fix: miscellaneous conversion of Provider<File> to RegularFileProvide…
KengoTODA/spotbugs-gradle-plugin-v2 pull request #54
Opened 2020-01-15 02:00 UTC by DPUkyle

…r and DirectoryProvider

 - This enables configuration of the tasks via Java, avoiding `SpotBugsTask#reports(Closure)`
 - Also add @Inject to SpotBugsTask constructor per https://guides.gradle.org/using-the-worker-api/#converting_to_the_worker_api

2020-01-16 04:51 UTC, KengoTODA requested changes
Seems nice, thank you. I found one problem around `$buildDir` handling, then created a patch to reproduce:
[patches.zip](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/files/4069370/patches.zip)

I also proposed a fix, please check this ZIP file.

2020-01-16 07:32 UTC, DPUkyle commented
Thank you for the patches; I will apply and update the PR tomorrow, 2020-01-16 US PT.

2020-01-16 18:56 UTC, DPUkyle commented
I knew one test fails for Gradle 6.1; I'm asking for help from one of the Gradle engineers.

2020-01-16 20:17 UTC, KengoTODA commented
Still have one problem:

> Cause 1: org.gradle.api.InvalidUserDataException: No value has been specified for property 'firstEnabledReport.outputLocation'.

I checked both of gradle/gradle#11189 and gradle/gradle#11923
it's strange that we face this problem even though we depend no internal API 🤔

2020-01-16 20:29 UTC, DPUkyle commented
Yes I agree it is strange; it is related to new APIs added in Gradle 6.1. I'm asking a Gradle engineer for help offline. I will be in touch. Thank you again for your patience and collaboration :bow:.

2020-01-16 20:36 UTC, KengoTODA commented
Thank you.

After you found a solution and commit it, please run `./gradlew spotlessApply` or `./gradlew` to reformat your code.

2020-01-16 22:10 UTC, KengoTODA commented
#60 introduced a mechanism to test with multiple gradle versions, please use it if possible.

2020-01-16 22:18 UTC, DPUkyle commented
Great, I will rebase and use it once I have a fix.

2020-01-18 09:14 UTC, KengoTODA commented
So that Gradle gave up supporting backward compatibility? What's the difference btw enabled and required?

2020-01-18 15:39 UTC, DPUkyle commented
> So that Gradle gave up supporting backward compatibility? 

I understand your frustration and I am not happy either - this was more difficult than it should be. In this case, directly instantiating the report classes was incorrect, instead objectFactory should be used. Gradle will apparently decorate the instance with missing methods. But how could we know this as it is not documented AFAIK. Further, while the Report API is a public interface I'm not sure any external plugins have successfully implemented it. Spotbugs v2 will be the best example :)

> What's the difference btw enabled and required?

I wish I knew. I think this additive change in a minor release is a mistake. Specifically, I believe the "decorate" functionality I mentioned above did not anticipate `getFirstEnabledReport()` is annotated with `@Nested`. I do not understand the intent of the new field.

As plugin authors I think we have no choice but to continue to put a strong emphasis on multi-version testing to protect ourselves against and adapt to the frequently-changing APIs. Also, if we can get this plugin added to Gradle's third-party suite (see #59), this might help them better understand the impact of their changes, and help us keep the plugin implementation more correct.

2020-01-19 02:58 UTC, KengoTODA approved these changes
Thanks for your great contribution!

To make release note simple and easy to understand, I will squash-and-merge these changes.

2020-01-19 02:59 UTC, merged